# Generated by Django 3.0.7 on 2020-08-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20200812_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='projects',
            field=models.ManyToManyField(related_name='project', to='project.Project'),
        ),
    ]
