# Generated by Django 3.0.7 on 2020-08-13 06:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20200813_0959'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 6, 17, 30, 975799, tzinfo=utc)),
        ),
    ]
