# Generated by Django 3.0.7 on 2020-08-13 08:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_client_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 8, 25, 36, 247072, tzinfo=utc)),
        ),
    ]
