# Generated by Django 3.0.7 on 2020-08-13 10:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20200813_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 13, 10, 48, 21, 806083, tzinfo=utc)),
        ),
    ]
